spring:
  application:
    name: nft-admin
server:
  port: 8090
alchemy:
  api-key: ${ALCHEMY_API_KEY}
  wallet-private-key: ${WALLET_PRIVATE_KEY}
springdoc:
  swagger-ui:
    tryItOutEnabled: true
    filter: true

management:
  server:
    port: 8070
    ssl:
      enabled: false
  metrics:
    distribution:
      percentiles:
        method.timed.server.http: 0.5, 0.95, 0.99
        spring.data.repository.invocations: 0.5, 0.95, 0.99
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
